export { default as RenameConfigPanel } from './RenameConfigPanel.vue'
export { default as ConvertConfigPanel } from './ConvertConfigPanel.vue'
export { default as CompressConfigPanel } from './CompressConfigPanel.vue'
export { default as QuickLinkPanel } from './QuickLinkPanel.vue'
export { default as QuickLinkConfigPanel } from './QuickLinkConfigPanel.vue'
export { default as UploadConfigModal } from './UploadConfigModal.vue'
